### ISSUE TITLE
[bug] DownloadPoeOvhData() -> MaxJsonLength Property

### ISSUE THREAD

**Issue by kernelENREK** [siegrest/Pricer#6]
File: PriceManager.cs
Method: DownloadPoeOvhData()

```
// Download JSON-encoded string
string jsonString = MainWindow.webClient.DownloadString("http://api.poe.ovh/get?league=" + Settings.league + "&parent=all");
```

The donwload seems 'ok', but when you try to deseriealize:

```
// Deserialize
List<PoeOvhEntry> tempDict = new JavaScriptSerializer().Deserialize<List<PoeOvhEntry>>(jsonString);

```
It's throws this exception:

> "Error during serialization or deserialization using JSON JavaScriptSerializer.The length of the string exceeds the value set in the maxJsonLength property. \ R \ nName of the parameter: input"

Useful info about exception: https://msdn.microsoft.com/en-us/library/system.web.script.serialization.javascriptserializer.maxjsonlength(v=vs.110).aspx

Maybe this is the 'problem':

`The maximum length of JSON strings. The default is 2097152 characters, which is equivalent to 4 MB of Unicode string data.
`

**How i fixed?**

1) Installing Newtonsoft.Json nuget package: https://www.nuget.org/packages/Newtonsoft.Json/11.0.2
2) Changing this on DownloadPoeOvhData(): (using Newtonsoft.Json instead JavaScriptSerializer)

```
// Deserialize (Fix bug 4 MB data)
List<PoeOvhEntry> tempDict = Newtonsoft.Json.JsonConvert.DeserializeObject<List<PoeOvhEntry>>(jsonString);
```

**Comment by siegrest** [comment]
It keeps throwing errors because I keep changing the API on poe.ovh. I'll create a separate API endpoint for this application that'll output a lot less data in the coming days.
